{% set name = "exempi" %}
{% set version = "2.4.5" %}
{% set sha256 = "406185feb88e84ea1d4b4251370be2991205790d7113a7e28e192ff46a4f221e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://libopenraw.freedesktop.org/download/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - boost >=1.64
    - expat 
    - zlib >=1.2.11
  run:
    - expat

test:
  commands:
    - test -f $PREFIX/lib/libexempi.dylib  # [osx]
    - test -f $PREFIX/lib/libexempi.so  # [linux]
    - test -f $PREFIX/bin/exempi
    - conda inspect linkages -p $PREFIX exempi  # [not win]
    - conda inspect objects -p $PREFIX exempi  # [osx]

about:
  home: http://libopenraw.freedesktop.org/wiki/Exempi
  license: BSD 3-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: 'exempi is a port of Adobe XMP SDK to work on UNIX'
  dev_url: https://github.com/hfiguiere/exempi

extra:
  recipe-maintainers:
    - quintusdias
