travis:
  secure:
    BINSTAR_TOKEN: eFYXwr63kypMTGLVNPWS1qWuHfj84DnmfOsb101W+cpnNE9O2fohA5qgOz+lV95MYYsdM/+v2PwraQkzyckq4Pe+VfC4y/z/SPgK04UnNTSqjbVOGFzITMYGSH866I8VlYxq2jJC1zPlklHunQ/9kEPsfPcmNTJMiW92hKSKISEI80yXTDihg0umRdT3QY1+k2nNj26NNXBLs31Mlp4Mq/OGxtHLk2mj/5EpCpzfZi63ZWjREwFJySrkBJk+f7XQeUgtxi2vI+0x9hOUOrPFwndAhw1AIx5SCZf3D7ExIr3r3kghqdFrscm+NMpCafRy5PH8oZnqgb5BgCFOm5S1kv/6qBZMW7H3PR1Cm84PDhO/BSA2Z2DUVjEF3XdpVUorr7ugD553e4WdXMFHoFDTDKB1b619Uv186gs28A986zBSX4Z2qQYvJ+z8miE9juVxGycKnhEMScjIWVHvBcSbDaRJ4oon9qAIUQlY4Qat3AnkzjnXFeCc7wV/XACpuaTsgKiF80bp5VYUtJtUBQjzqqQj3ted3TQ0O+IvcLJ8/2W0NY3xxQoVWmy+AjqJc8tJlpoLupJ7/f3oeWNI668W28b4NIl0ZDNU1XZ1vMMuGXtZVUt1NlF5XEi5CdPBOWMjCBZJ/2byjiRULPeWHs59z2+xv9Z8Fd6SvwI4cij1/I0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
