travis:
  secure:
    BINSTAR_TOKEN: ngqds4ejUFwrI3UGtp2IpIHCLV0Eoe5+CGrIomYn1FxVPCtrZ8G5IEnjbph/UwsQxn0SgYXPGnvFChJwlvpGZqGD/bFp1hvHRiQDRQINtmPnwwu28xgb7YkdcDjY1l97aQFVHcwzr0/CSjUzLL7E4GYdbTjOM4n9qn2V000Vr50VKpkaxE+OpHO3565QXBW0rPmp4YtecUT6qfXU7bB/Fr1OmUH7QlSKUJvE5Lqs1YyxaUU6HpgWJXL+1JDqSlAZAeyuHYLakwNTSWazAnRxUfUZaedfAkDtAJg+tqqeT1jtCFlbCfytAhPsVf9kC0K5g4hlijKeoYm2Qeu60wWBJZrtsTAwKBMIX6RACGoz7lSOscpWHRhLMixwsequ/a7XnA2X6IqrFwLdE0+eOMfY4fU2oaj81yDkv4CTPQcEJC/w/hqUu9uBoZsGQWF30YQh6L2kZkjoeDydemnZ85xxJaSR6iOlHpPnHk4Ibauqgeos3+VGRBzIu1q5AUcPDb3XB0vhbwphIFwyLysetT4Q+nLQL7WD63DVWw0CO+JNa0SOIultg6+ZZgV9Y6anlSYkGWeY3ZubBjW9SYdrZ2c4BncNakwHxN9Za4jpxbmL/beet21TGabtQDLM2yH6T4g/PiDA7v4NHEDqH2k1O2ETCwCHIgFVXSILD3gvUUHGxSA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
